services:
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile.front
    ports:
      - "3000:5173"
    depends_on:
      - back
    volumes:
      - ./front:/app
      - /app/node_modules

  back:
    build: 
      context: .
      dockerfile: ./back/Dockerfile.back
    ports:
      - "8080:8080"
      - "9229:9229"
    depends_on:
      - redis
    volumes:
      - ./back:/app/back
      - /app/back/node_modules
  
  redis:
    image: "redis"
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data: