name: app-prod

services:
  front:
    image: app-front-prod
    container_name: app-front-prod
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./front/Dockerfile.prod
    ports:
      - "3000:3000"
    depends_on:
      - back

  back:
    image: app-back-prod
    container_name: app-back-prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./back/Dockerfile.prod
    env_file:
      - ./.env.back
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - ./redis_data_prod:/data

  rabbitmq:
    image: rabbitmq:4-alpine
    restart: unless-stopped
    env_file:
      - ./.env.rabbitmq

  adapter:
    image: app-adapter-prod
    container_name: app-adapter-prod
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./adapter/Dockerfile.prod
    env_file:
      - ./.env.adapter
    depends_on:
      - rabbitmq