name: app-dev

services:
  front:
    image: app-front-dev
    container_name: app-front-dev
    build: 
      context: .
      dockerfile: ./front/Dockerfile.dev
    ports:
      - "3000:5173"
    environment:
      - BACKEND_URL=http://back:3000
      - SOCKETS_URL=http://back:8080
    depends_on:
      - back
    volumes:
      - ./front:/app/front
      - front_node_modules:/app/front/node_modules

  back:
    image: app-back-dev
    container_name: app-back-dev
    build:
      context: .
      dockerfile: ./back/Dockerfile.dev
    ports:
      - "9229:9229"
    environment:
      - REDIS_URL=redis://redis:6379
    env_file:
      - ./.env.back
      - ./.env.versiones
    depends_on:
      - redis
      - rabbitmq
    volumes:
      - ./back:/app/back
      - back_node_modules:/app/back/node_modules

  redis:
    image: "redis:alpine"
    volumes:
      - ./redis_data:/data

  rabbitmq:
    image: rabbitmq:4-management
    restart: unless-stopped
    ports:
      - "15672:15672"
    env_file:
      - ./.env.rabbitmq

  adapter:
    image: app-adapter-dev
    container_name: app-adapter-dev
    build:
      context: .
      dockerfile: ./adapter/Dockerfile.dev
    ports:
      - "9230:9229"
    env_file:
      - ./.env.adapter
    depends_on:
      - rabbitmq
    volumes:
      - ./adapter:/app/adapter
      - /app/adapter/node_modules

volumes:
  front_node_modules:
  back_node_modules: