FROM node:lts-alpine AS builder

WORKDIR /app/front

COPY shared ../shared
COPY front/package.json ./
COPY front/package-lock.json ./

RUN npm ci

COPY front/src ./src
COPY front/public ./public
COPY front/index.html ./
COPY front/vite.config.ts ./

RUN npm run build

FROM nginx:alpine

COPY --from=builder /app/front/dist-front /usr/share/nginx/html
COPY front/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]