FROM node:lts-alpine AS builder

WORKDIR /app/adapter

COPY adapter/package.json ./
COPY adapter/package-lock.json ./

RUN npm ci

COPY adapter/src ./src
COPY adapter/tsconfig.json ./

RUN npm run build
RUN npm run minify

FROM node:lts-alpine

WORKDIR /app/adapter

COPY --from=builder /app/adapter/dist/main.min.js ./dist/
COPY adapter/package.json ./
COPY adapter/package-lock.json ./

RUN npm ci --omit=dev

CMD ["node", "dist/main.min.js"]
