on: [push, pull_request]

jobs:
  ci-back:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./back
    steps:
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run test