on: [push, pull_request]



jobs:
  ci-back:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-reports-${{ github.ref }}
      cancel-in-progress: false
    defaults:
      run:
        working-directory: Aplicacion/back
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test

      - name: Subir reporte
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.REPORTS_TOKEN }}
          external_repository: N3STOR173/Reportes-Estadisticas-Logros
          publish_dir: Aplicacion/back/test-report
          destination_dir: back/${{ github.ref_name }}/report

      - name: Subir coverage
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.REPORTS_TOKEN }}
          external_repository: N3STOR173/Reportes-Estadisticas-Logros
          publish_dir: Aplicacion/back/coverage
          destination_dir: back/${{ github.ref_name }}/coverage

  ci-front:
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-reports-${{ github.ref }}
      cancel-in-progress: false
    defaults:
      run:
        working-directory: Aplicacion/front
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run test

      - name: Subir reporte
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.REPORTS_TOKEN }}
          external_repository: N3STOR173/Reportes-Estadisticas-Logros
          publish_dir: Aplicacion/front/test-report
          destination_dir: front/${{ github.ref_name }}